Render helm charts for checkov
Checkov wasn't scanning the chart manifests because of missing required
values. Fixes for the unearthed issues are included.

Signed-off-by: Alex Misstear <amisstea@redhat.com>

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -22,12 +22,22 @@ jobs:
 
       - name: Run checkov
         uses: bridgecrewio/checkov-action@v12
+        id: checkov
         with:
           output_format: cli,sarif
           output_file_path: console,results.sarif
+          var_file: test/dummy-vars.yaml
+        env:
+          HELM_NAMESPACE: dummy-ns
         continue-on-error: true
 
       - name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: results.sarif
+
+      - name: Report failure
+        if: steps.checkov.outcome == 'failure'
+        run: |
+          echo "The checkov scan resulted in failure. See the output of the above step."
+          exit 1
